version: '2.1'
services:

  #
  # tester container, using canyan-tester
  #
  tester:
    image: 'canyan/canyan-tester:master'
    environment:
      API_ENDPOINT: http://rating-api:8000
      TARGET_KAMAILIO: kamailio:5060
      TARGET_OPENSIPS: opensips:5060
    volumes:
      - "./tests/:/tests/"
    command: sh -c "while true; do sleep 5; done;"
