version: '2'
services:
    mongodb:
        image: 'bitnami/mongodb:4.0'
        ports:
        - "27017:27017"
        volumes:
        - ./data/mongodb:/opt/mongodb
    rabbitmq:
        image: 'bitnami/rabbitmq:3.7'
        ports:
        - "5672:5672"
        - "15672:15672"
        environment:
        - RABBITMQ_PASSWORD=password
        volumes:
        - ./data/rabbitmq:/bitnami/rabbitmq
    api:
        image: 'canyan/rating-api:master'
        ports:
        - "8000:8000"
    agent:
        image: 'canyan/rating-agent:master'
        environment:
        - MESSAGEBUS_URI=pyamqp://user:password@rabbitmq:5672//
        ports:
        - "8080:8000"
    engine:
        image: 'canyan/rating-engine:master'
